version: "3"

services:

  application:
    container_name: test_app
    image: golang:1.16-alpine
    volumes:
      - "./app/:/usr/app/"
    command: >
      /bin/sh -c "cd /usr/app && go mod download && go run main.go"

  logstash:
    restart: on-failure
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:7.14.0
    environment:
      LS_LOG_LEVEL: warn
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro"
      - "./logstash/config/pipelines:/usr/share/logstash/config/pipelines:ro"
    command: >
      bash -c "bin/logstash-plugin install logstash-output-clickhouse && logstash"

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.14.0
    entrypoint: filebeat -e -strict.perms=false
    user: root
    depends_on:
      - application
      - logstash
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "./app/logs:/var/app/log:ro"

  clickhouse:
    image: yandex/clickhouse-server:21.3-alpine
    volumes:
      - "./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
      - "./clickhouse/data/:/var/lib/clickhouse/"
      - "./clickhouse/log/:/var/log/clickhouse-server/"
    healthcheck:
      test: [ "CMD", "ping", "-c", "4", "localhost:8123" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8123:8123"

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    depends_on:
      - clickhouse
    ports:
      - "8089:80"

#  grafana:
#    image: grafana/grafana:latest
#    environment:
#      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource
#    ports:
#      - "51124:3000"

#  vector-client:
#    container_name: vector-client
#    image: timberio/vector:0.8.2-alpine
#    environment:
#      RUST_BACKTRACE: full
#    depends_on:
##      - vector-server
#      - application
#    volumes:
#      - "./app/logs/:/usr/app/"
#      - "./vector-client/vector.toml:/etc/vector/vector.toml"
#    command: ["--config", "/etc/vector/vector.toml", "-w"]
#
#  vector-server:
#    container_name: vector-server
#    image: timberio/vector:0.8.2-alpine
#    environment:
#      RUST_BACKTRACE: full
#    depends_on:
#      - application
#      - clickhouse
#    volumes:
#      - "./app/logs/logrus.log:/usr/app/logs/logrus.log"
#      - "./vector-server/vector.toml:/etc/vector/vector.toml"
#    command: ["--config", "/etc/vector/vector.toml", "-w"]
